### ISSUE TITLE
"Path must be a string" returned when giving an array of source files

### ISSUE THREAD

**Issue by WolfieZero** [JeffreyWay/Laravel-Elixir-Rollup#6]
In my gulpfile I have `mix.rollup(['app.js', 'router.js']);`, but this returns:

```
TypeError: Path must be a string. Received [ 'app/js/app.js', 'app/js/router.js' ]
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1148:7)
    at resolveId (/blahblah/my-project/node_modules/rollup/dist/rollup.js:6907:71)
    at /blahblah/my-project/node_modules/rollup/dist/rollup.js:1574:32
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

I presume this is more to do with Rollup not supporting an array of files, but the Elixir docs suggest otherwise.

**Comment by laracasts** [comment]
Fixed.

**Comment by MightyPork** [comment]
This is still broken, please review it..

```
(node:20609) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Path must be a string. Received [ 'resources/assets/js/utils/*/**/*',
  'resources/assets/js/manage/BaseManageSetting.js',
  'resources/assets/js/manage/Thermostat.js',
  'resources/assets/js/manage/ThermostatProgramEditor.js',
  'resources/assets/js/manage/Humidistat.js',
  'resources/assets/js/manage/Planner.js',
  'resources/assets/js/manage/ElectroAcean.js',
....
```

Specifically, I've been using babel(), but that's now gone and Elixir told me to use rollup() instead... doesn't seem to work

**Comment by Gliba** [comment]
Rollup broken, webpack working

**Comment by AlexH-HankIT** [comment]
It's also broken for me:

`(node:4788) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Path must be a string. Received [ 'resources\\assets\\js\\category\\index.js'
  'resources\\assets\\bower_components\\bootstrap-table\\dist\\extensions\\editable\\bootstrap-table-editable.js' ]`

**Comment by rafapaulin** [comment]
still broken for me too

**Comment by JonathanFoley** [comment]
Did anyone manage to fix this? Experiencing the same issue.

**Comment by MaartenStaa** [comment]
I'm also having this same issue, versions:

- gulp: 3.9.1
- laravel-elixir: 6.0.0-15
- laravel-elixir-rollup-official: 1.1.0

In other words, the newest of each.

Stack trace:

```
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1167:7)
    at defaultResolver (/Users/me/the-project/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:49:71)
    at /Users/me/the-project/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:519:15
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by joshwhatk** [comment]
+1

**Comment by thatguy76** [comment]
What is the fix for this?
